name: tes
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - opencv
  - cudatoolkit=11.8
  - scikit-learn
  - tqdm
  - pip:
    - torch>=2.3.1
    - torchvision>=0.18.1
    - hydra-core
    - mrcfile
    - onnxruntime