name: test_env_name
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - opencv
  - cudatoolkit=11.8
  - scikit-learn
  - tqdm
  - imageio
  - pandas
  - matplotlib
  - scipy
  - psutil
  - pip:
    - torch>=2.3.1
    - torchvision>=0.18.1
    - hydra-core
    - mrcfile
    - onnxruntime
    - imageio
    - iopath
    - timm
    - fairscale
    - fvcore
    - submitit
    - black
    - termcolor